CREATE OR REPLACE PROCEDURE GRIZZLY_DB.SILVER.CLEAN_CUSTOMERS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CREATE OR REPLACE TABLE GRIZZLY_DB.SILVER.CUSTOMERS AS
    SELECT
        UPPER(TRIM(CUSTOMER_ID))::STRING AS CUSTOMER_ID,

        CAST(CURRENT_AGE AS FLOAT)       AS CURRENT_AGE,
        CAST(RETIREMENT_AGE AS FLOAT)    AS RETIREMENT_AGE,
        CAST(BIRTH_YEAR AS FLOAT)        AS BIRTH_YEAR,
        CAST(BIRTH_MONTH AS FLOAT)       AS BIRTH_MONTH,

        INITCAP(TRIM(GENDER))  AS GENDER,
        INITCAP(TRIM(ADDRESS)) AS ADDRESS,

        CAST(LATITUDE AS FLOAT)          AS LATITUDE,
        CAST(LONGITUDE AS FLOAT)         AS LONGITUDE,

        CAST(REPLACE(REPLACE(PER_CAPITA_INCOME, ''$'', ''''), '','', '''') AS FLOAT) AS PER_CAPITA_INCOME,
        CAST(REPLACE(REPLACE(YEARLY_INCOME, ''$'', ''''), '','', '''') AS FLOAT)     AS YEARLY_INCOME,
        CAST(REPLACE(REPLACE(TOTAL_DEBT, ''$'', ''''), '','', '''') AS FLOAT)        AS TOTAL_DEBT,

        CAST(CREDIT_SCORE AS FLOAT)       AS CREDIT_SCORE,
        CAST(NUM_CREDIT_CARDS AS FLOAT)   AS NUM_CREDIT_CARDS

    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY UPPER(TRIM(CUSTOMER_ID))
                   ORDER BY CUSTOMER_ID
               ) AS RNK
        FROM GRIZZLY_DB.BRONZE.CUSTOMERS
    )
    WHERE RNK = 1
      AND CUSTOMER_ID IS NOT NULL;

    RETURN ''CLEAN_CUSTOMERS: Loaded to SILVER.CUSTOMERS successfully'';
END;
';