CREATE OR REPLACE PROCEDURE GRIZZLY_DB.SILVER.CLEAN_MERCHANTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CREATE OR REPLACE TABLE GRIZZLY_DB.SILVER.MERCHANTS AS
    SELECT
        UPPER(TRIM(MERCHANT_ID))::STRING AS MERCHANT_ID,
        INITCAP(TRIM(MERCHANT_NAME))     AS MERCHANT_NAME,
        INITCAP(TRIM(MERCHANT_CITY))     AS MERCHANT_CITY,
        UPPER(TRIM(MERCHANT_STATE))      AS MERCHANT_STATE,
        LPAD(TO_VARCHAR(TRY_TO_NUMBER(ZIP)), 5, ''0'') AS ZIP,
        TRY_TO_NUMBER(MCC)               AS MCC,
        INITCAP(TRIM(MCC_DESCRIPTION))   AS MCC_DESCRIPTION
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                 PARTITION BY MERCHANT_ID
                 ORDER BY MERCHANT_NAME
               ) AS RNK
        FROM GRIZZLY_DB.BRONZE.MERCHANTS
    )
    WHERE RNK = 1
      AND MERCHANT_ID IS NOT NULL;

    RETURN ''CLEAN_MERCHANTS: Loaded to SILVER.MERCHANTS'';
END;
';