CREATE OR REPLACE PROCEDURE GRIZZLY_DB.SILVER.CLEAN_DISPUTES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CREATE OR REPLACE TABLE GRIZZLY_DB.SILVER.DISPUTES AS
    SELECT
        UPPER(TRIM(DISPUTE_ID))::STRING      AS DISPUTE_ID,
        UPPER(TRIM(TRANSACTION_ID))::STRING  AS TRANSACTION_ID,
        INITCAP(TRIM(FEEDBACK))              AS FEEDBACK,
        TRY_TO_DATE(DISPUTE_RAISED)          AS DISPUTE_RAISED,
        TRY_TO_DATE(DISPUTE_RESOLVED)        AS DISPUTE_RESOLVED,
        INITCAP(TRIM(STATUS))                AS STATUS,
        TRY_TO_NUMBER(RESOLUTION_DAYS)       AS RESOLUTION_DAYS,
        UPPER(TRIM(REASON_CODE_STD))         AS REASON_CODE_STD,
        INITCAP(TRIM(REASON_CATEGORY))       AS REASON_CATEGORY,
        UPPER(TRIM(STATUS_STD))              AS STATUS_STD,
        UPPER(TRIM(UNIFIED_TXN_ID))::STRING  AS UNIFIED_TXN_ID
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                 PARTITION BY DISPUTE_ID
                 ORDER BY DISPUTE_RAISED DESC
               ) AS RNK
        FROM GRIZZLY_DB.BRONZE.DISPUTES
    )
    WHERE RNK = 1
      AND DISPUTE_ID IS NOT NULL;

    RETURN ''CLEAN_DISPUTES: Loaded to SILVER.DISPUTES'';
END;
';