CREATE OR REPLACE PROCEDURE GRIZZLY_DB.SILVER.CLEAN_BRONZE_TO_SILVER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CALL CLEAN_CUSTOMERS();
    CALL CLEAN_CARDS();
    CALL CLEAN_MERCHANTS();
    CALL CLEAN_TRANSACTIONS();
    CALL CLEAN_DISPUTES();

    RETURN ''BRONZE → SILVER cleaning complete for all tables.'';
END;
';