CREATE OR REPLACE FUNCTION GRIZZLY_DB.GOLD.TF_DISPUTE_ASOF("ASOF_DATE" DATE)
RETURNS TABLE ("DISPUTE_CASE_ID" VARCHAR, "LAST_EVENT_TS" TIMESTAMP_NTZ(9), "STAGE_KEY" NUMBER(38,0), "STAGE_CODE" VARCHAR, "IS_TERMINAL" BOOLEAN, "MERCHANT_ID" VARCHAR, "REASON_CODE" VARCHAR, "DISPUTED_AMOUNT" NUMBER(18,2))
LANGUAGE SQL
AS '
  WITH L AS (
    SELECT
      f.DISPUTE_CASE_ID,
      f.EVENT_TS,
      f.STAGE_KEY,
      f.MERCHANT_ID,
      f.REASON_CODE,
      f.DISPUTED_AMOUNT,
      f.LOAD_TS
    FROM GOLD.FACT_DISPUTE f
    WHERE f.EVENT_TS <= TIMESTAMP_NTZ_FROM_PARTS(
                           YEAR(asof_date), MONTH(asof_date), DAY(asof_date),
                           23, 59, 59)
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY f.DISPUTE_CASE_ID
      ORDER BY f.EVENT_TS DESC, f.LOAD_TS DESC
    ) = 1
  )
  SELECT
    L.DISPUTE_CASE_ID,
    L.EVENT_TS             AS LAST_EVENT_TS,
    L.STAGE_KEY,
    S.STAGE_CODE,
    S.IS_TERMINAL,
    L.MERCHANT_ID,
    L.REASON_CODE,
    L.DISPUTED_AMOUNT
  FROM L
  LEFT JOIN GOLD.DIM_DISPUTE_STAGE S
    ON S.STAGE_KEY = L.STAGE_KEY
';